export const barrios = [
  "8 de Abril",
  "Aeropuerto",
  "Alberdi",
  "Almirante Brown",
  "América del Sur",
  "Autonomía",
  "Belgrano",
  "Bruno Volta",
  "Cabildo",
  "Cáceres",
  "Campo Contreras",
  "Centenario",
  "Centro",
  "Colón",
  "Congreso",
  "Coronel Borges",
  "Don Bosco",
  "El Vinalar",
  "Ejército Argentino",
  "Francisco de Aguirre",
  "Francisco Solano",
  "Huaico Hondo",
  "Independencia",
  "Industria",
  "Islas Malvinas",
  "Jardín",
  "John Kennedy",
  "Jorge Newbery",
  "Juan Díaz de Solís",
  "Juan Felipe Ibarra",
  "Juan XXIII",
  "Juramento (Barrio residencial)",
  "La Católica",
  "La Costa",
  "Los Flores",
  "Los Inmigrantes",
  "Madres de Plaza de Mayo",
  "Mariano Moreno",
  "Mosconi",
  "Parque Aguirre",
  "Primera Junta",
  "Ramón Carrillo",
  "Reconquista",
  "Rivadavia",
  "Saint Germaint",
  "Salvador Mazza",
  "San Martín",
  "Santa Lucía",
  "Santa Rosa de Lima",
  "Sargento Cabral",
  "Sáenz Peña",
  "Siglo XIX",
  "Siglo XX",
  "Siglo XXI",
  "Tradición",
  "Virgen de Guadalupe",
  "750 viviendas",
  "750 viviendas sector duplex",
];

export const ciudades = [
  "Añatuya",
  "Bandera",
  "Belgrano",
  "Beltrán",
  "Campo Gallo",
  "Clodomira",
  "Colonia Dora",
  "Fernández",
  "Frías",
  "General Taboada",
  "Ingeniero Forres",
  "La Banda",
  "Santiago del Estero",
];

export const barriosLaBanda = [
  "8 de Abril",
  "Alberdi",
  "Banda Este",
  "Banda Norte",
  "Banda Oeste",
  "Banda Sur",
  "Belgrano",
  "Centro",
  "Central argentino",
  "El paraíso",
  "La Dársena",
  "Los Lagos",
  "Los Naranjos",
  "Mamantula",
  "Procrear",
  "San Carlos",
  "San Fernando",
  "San Martín",
  "Santa Rosa",
  "Sarmiento",
  "Villa del Carmen",
  "Villa Elisa",
  "Villa Griselda",
  "Villa Inés",
  "Villa Lourdes",
  "Villa María",
  "Villa Nueva",
  "25 de mayo",
  "Rio dulce",
  "El cruce",
  "El matadero",
  "Los quiroga",
];
